#!/bin/bash
## usage - sudo ./script/bootstrap
## tested with Ruby 2.1.2

echo 'installing spiceweasel...'
# gem install spiceweasel
git clone 'https://github.com/mattray/spiceweasel.git' /tmp/spiceweasel
cd /tmp/spiceweasel/
git checkout 2.8
gem build spiceweasel.gemspec
gem install spiceweasel-2.8.0.gem

# Vagrant needs to install nokogiri: http://nokogiri.org/tutorials/installing_nokogiri.html"
echo "installing nokogiri dependency for vagrant plugins"
if [ "$(uname)" == "Darwin" ]; then
  xcode-select --install
  brew install libxml2 libxslt libiconv
  brew link libxml2 libxslt libiconv
  install nokogiri -- --with-iconv-dir=/usr/local/Cellar/libiconv/1.14/
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sudo yum install -y rubygem-nokogiri
  sudo yum install -y gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel
  sudo gem install nokogiri -- --with-xml2-lib=/usr/local/lib --with-xml2-include=/usr/local/include/libxml2 --with-xslt-lib=/usr/local/lib --with-xslt-include=/usr/local/include
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
  gem install nokogiri
fi

# install vagrant plugins
echo "installing vagrant plugins"
gem install knife-vagrant2
gem install knife-solo
vagrant plugin install vagrant-berkshelf --plugin-source http://rubygems.org
vagrant plugin install vagrant-butcher --plugin-source http://rubygems.org

rbenv rehash
